### GET all accounts
GET http://localhost:8080/api/account/getAccounts

### GET account by id
GET http://localhost:8080/api/account/getAccounts/1

### GET current account balance using account id
GET http://localhost:8080/api/account/getCurrentBalance/3

###
POST http://localhost:8080/api/account/createAccount
Content-Type: application/json

{
  "accountName": "CHECKING",
  "startingBalance": 1000
}

###
DELETE http://localhost:8080/api/account/deleteAccount/3

###
DELETE http://localhost:8080/api/account/deleteAll