### GET all accounts
GET http://localhost:8080/api/account/getAccounts

### GET account by id
GET http://localhost:8080/api/account/getAccounts/5

### GET current account balance using account id
GET http://localhost:8080/api/account/getCurrentBalance/

###
POST http://localhost:8080/api/account/createAccount
Content-Type: application/json

{
  "accountName": "CHECKING",
  "startingBalance": 1000
}

###
PUT http://localhost:8080/api/account/updateAccount/6
Content-Type: application/json

{
  "accountName": "SAVINGS",
  "startingBalance": 2000
}

###
DELETE http://localhost:8080/api/account/deleteAccount/7

###
DELETE http://localhost:8080/api/account/deleteAll