###
POST http://localhost:8080/api/transaction/createTransaction
Content-Type: application/json

{
  "accountId": 3,
  "amount": 50,
  "type": "INCOME",
  "category": "FOOD",
  "description": "Burger King",
  "transactionDate": "2026-07-06"
}

### Update Transactions by TransactionId
PUT http://localhost:8080/api/transaction/updateTransaction/2
Content-Type: application/json

{
  "accountId": 1,
  "amount": 1000,
  "type": "EXPENSE",
  "category": "FOOD",
  "description": "Chipotle",
  "transactionDate": "2026-07-07"
}

### Get all transactions
GET http://localhost:8080/api/transaction/getAllTransactions

### GET all transactions by accountID
GET http://localhost:8080/api/transaction/getTransactions/2

### GET all transactions by category
GET http://localhost:8080/api/transaction/getTransactionsByCategory/UTILITIES

### GET all transactions by type
GET http://localhost:8080/api/transaction/getTransactionsByType/INCOME

### GET all transactions in between two dates
GET http://localhost:8080/api/transaction/getTransactionsInBetweenDates/2026-07-07,2026-07-08

### GET all transactions greater than specified amount
GET http://localhost:8080/api/transaction/findTransactionsGreaterThanAmount/100