###
POST http://localhost:8080/api/transaction/createTransaction
Content-Type: application/json

{
  "accountId": 3,
  "amount": 50,
  "type": "INCOME",
  "category": "FOOD",
  "description": "Burger King",
  "transactionDate": "2026-07-06"
}

### GET all transactions
GET http://localhost:8080/api/transaction/getTransactions/4