###
POST http://localhost:8080/api/transaction/createTransaction
Content-Type: application/json

{
  "accountId": 1,
  "amount": 100.00,
  "type": "INCOME",
  "category": "FOOD",
  "description": "Burger King",
  "transactionDate": "07-06-2026"
}

### Update Transactions by TransactionId
PUT http://localhost:8080/api/transaction/updateTransaction/12
Content-Type: application/json

{
  "accountId": 1,
  "amount": 1000,
  "type": "EXPENSE",
  "category": "FOOD",
  "description": "Chipotle",
  "transactionDate": "07-06-2026"
}

### Get all transactions
GET http://localhost:8080/api/transaction/getAllTransactions

### GET all transactions by accountID
GET http://localhost:8080/api/transaction/getTransactions/85

### GET all transactions by category
GET http://localhost:8080/api/transaction/getTransactionsByCategory/TRANSPORTATION

### GET all transactions by type
GET http://localhost:8080/api/transaction/getTransactionsByType/INCOME

### GET all transactions in between two dates
GET http://localhost:8080/api/transaction/getTransactionsInBetweenDates/2026-05-07,2026-05-08

### GET all transactions greater than specified amount
GET http://localhost:8080/api/transaction/findTransactionsGreaterThanAmount/10000

### DELETE transactions by ID
DELETE http://localhost:8080/api/transaction/deleteTransactions/25

### DELETE all transactions
DELETE http://localhost:8080/api/transaction/deleteAllTransactions