spring.application.name=Personal-Finance-Tracker-API
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_tracker
spring.datasource.username=finance_user
spring.datasource.password=finance_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true